Crowd_Funding/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('about/', include('company_profile.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('donor_auth.urls')),
    path('news/', include('news.urls')),
    path('profile/', include('user_profile.urls')),
    path('programs/', include('program.urls')),
    path('', include('landing_page.urls')),
]

donor_auth/urls.py
from django.urls import path
from . import views
import donation.views as donation_views

app_name = "donor_auth"

urlpatterns = [
    path('is_authenticated/', views.is_auth, name="is_auth"),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout")
]

landing_page/urls.py
from django.urls import path
from . import views

app_name = "landing_page"

urlpatterns = [
    path('', views.landing_page, name="landing_page")
]

news/urls.py
from django.urls import path
from .views import *

app_name = "news"
 
urlpatterns = [
    path('', news_page, name = "news_page")
]

program/urls.py
from django.urls import path
from . import views
import donation.views as donation_views

app_name = "program"

urlpatterns = [
    path('', views.program_list, name="program_list"),
    path('<slug>/', views.program_details, name="program_details"),
    path('<slug>/donate/', donation_views.program_donate, name="program_donate")
]

user_profile/urls.py
from django.urls import path
from . import views
import donation.views as donation_views

app_name = "user_profile"

urlpatterns = [
    path('', views.user_profile, name="user_profile"),
]

templates/base_layout.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="google-signin-client_id" content="302110534751-9kjukh2b0rrhk1ssv2o55cgm4kllbm3q.apps.googleusercontent.com">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>{{ page_title }}</title>
    <link rel="shortcut icon" href="{% static 'img/icon.png' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'styles/styles.css' %}" >
    <link rel="stylesheet" href="{% static 'styles/ctmButton.css' %}" >
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
    <script src="https://apis.google.com/js/platform.js"></script>
    <script>
        var login_url = "{% url 'donor_auth:login' %}";
        var logout_url = "{% url 'donor_auth:logout' %}";
        var is_auth_url = "{% url 'donor_auth:is_auth' %}";
    </script>
</head>

<body data-spy="scroll" data-target=".navbar" data-offset="0">

{% if navs %}
    {% include 'header.html' %}
{% endif %}

{% block content %}
{% endblock %}

{% if footer %}
    {% include 'footer.html' %}
{% endif %}

    <div class="modal fade" id="LogInModal" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Logged In</h4>
                </div>
                <div class="modal-body">
                    <p id="log-greet"></p>
                </div>
                <div class="modal-footer">
                    <a href="{% url 'news:news_page' %}" class="btn btn-default">Continue</a>
                </div>
            </div>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="https://apis.google.com/js/api:client.js"></script>
    <script type="text/javascript" src="{% static 'smoothScroll.js' %}"></script>
    <script type="text/javascript" src="{% static 'scripts/auth.js' %}"></script>
    <script type="text/javascript" src="{% static 'scripts/validation.js' %}"></script>
    <script type="text/javascript" src="{% static 'scripts/testimony.js' %}"></script>
</body>
</html>

templates/footer.html
<footer class="text-center bold blue-grad-bg white-text">
    {{ footer }}
</footer>

templates/header.html
<header class="sticky-top">
    <nav class="navbar navbar-expand-lg navbar-dark blue-grad-bg">
        <a class="navbar-brand" href="{% url 'landing_page:landing_page' %}"><span class="brand white-text">CareShare</span></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="true" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link bold white-text" href="{% url 'program:program_list' %}"><span class="active-ref">Programs</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link bold white-text" href="{% url 'news:news_page' %}"><span class="active-ref">News</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link bold white-text" href="{% url 'company_profile:about' %}"><span class="active-ref">About Us</span></a>
                </li>
                {% if request.session.user_id %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle bolder white-text" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <span class="active-ref">{{ request.session.name }}</span>
                        <img class="profile-pic" src="{{ request.session.picture }}">
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        {% csrf_token %}
                        <a class="dropdown-item bold black-text" href="{% url 'user_profile:user_profile' %}">Profile</a>
                        <a class="dropdown-item bold black-text" href="#" onclick="signOut()"><span class="active-ref">Sign Out</span></a>
                    </div>
                </li>
                {% else %}
                <li class="nav-item">
                    {% csrf_token %}
                    <div id="gSignInWrapper">
                        <div id="customBtn" class="customGPlusSignIn">
                            <span class="nav-link bolder white-text">Sign In</span>
                        </div>
                    </div>      
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>
</header>