Crowd_Funding/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('about/', include('company_profile.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('donor_auth.urls')),
    path('news/', include('news.urls')),
    path('profile/', include('user_profile.urls')),
    path('programs/', include('program.urls')),
    path('', include('landing_page.urls')),
]

news/urls.py
from django.urls import path
from .views import *

app_name = "news"
 
urlpatterns = [
    path('', news_page, name = "news_page")
]

program/urls.py
from django.urls import path
from . import views
import donation.views as donation_views

app_name = "program"

urlpatterns = [
    path('', views.program_list, name="program_list"),
    path('<slug>/', views.program_details, name="program_details"),
    path('<slug>/donate/', donation_views.program_donate, name="program_donate")
]

news/models.py
from django.db import models

# Create your models here.
class News(models.Model):
    title = models.CharField(max_length=100)
    content = models.CharField(max_length=1000)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = "News"

news/views.py
from django.shortcuts import render
from .models import *

# Create your views here.

response = {}
def news_page(request):
    news_list = News.objects.all()
    response = {
        "page_title": "News Page",
        "news_list" : news_list,
        "navs" : True,
        'footer' : 'CareShare, est.2018'
    }
    return render(request, 'news.html', response)

news/templates/news.html
{% extends 'base_layout.html' %}

{% load static from staticfiles %}

{% block content %}

<div class="w-100 full-height d-flex align-items-center main">
    <section class="container" id="news">
        <div class="text-center">
            <div class="text-center section-title margin-top-7">
                <h2 class="blue-text bolder">News</h2>
            </div>
        </div>
        <div>
            {% for news in news_list %}
                <div class="white-bg white-border card">
                    <div class="card-body row">
                        <div class="col-md-9"> 
                            <h3 class="card-title blue-text text-left">{{ news.title }}</h3>
                            <br>
                            <h6 class="card-subtitle mb-2 black-text text-left">{{ news.content }}</h6>
                        </div>
                        <div class="col-md-3" id="donation-list">
                            <h5 class="blue-text text-left"> Donation List: </h5>
                            <br>
                            <ul id="donation-list-ul">
                                {% for program in news.programs.all %}
                                    <li>
                                        <a class="light-blue-text bold" href="{% url 'program:program_details' slug=program.slug %}">
                                            {{ program.name }}
                                        </a> 
                                    </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </section>
</div>

{% endblock %}